spring:
  profiles:
    active: local

logback:
  access:
    config: classpath:logback/logback-access.xml

---
spring.profiles: local
spring:
  profiles:
    include:
      - db
      - oauth

logging:
  config: classpath:logback/logback-local.xml

---
spring.profiles: prod
spring:
  profiles:
    include:
      - db
      - oauth

logging:
  config: classpath:logback/logback-prod.xml

---
spring.profiles: dev
spring:
  profiles:
    include:
      - db
      - oauth

logging:
  config: classpath:logback/logback-dev.xml
