ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-categories]]
== Categories

[[resources-categories-create]]
=== 카테고리 추가

operation::categories/create[snippets='http-request,request-fields,http-response,response-headers,response-fields']

[[resources-categories-get-list]]
=== 카테고리 전체 조회

operation::categories/get/List[snippets='http-request,http-response,response-fields']

[[resources-categories-update]]
=== 카테고리 수정

operation::categories/update[snippets='http-request,request-fields,http-response']

[[resources-categories-tags-update]]
=== 태그의 카테고리 수정

operation::categories/tags/update[snippets='http-request,path-parameters,http-response']

[[resources-categories-delete]]
=== 카테고리 삭제

operation::categories/delete[snippets='http-request,path-parameters,http-response']

[[resources-tags]]
== Tags

[[resources-tags-create]]
=== 태그 추가

operation::tags/create[snippets='http-request,request-fields,http-response,response-headers,response-fields']

[[resources-tags-get]]
=== 태그 조회

operation::tags/get[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-tags-delete]]
=== 태그 삭제

operation::tags/delete[snippets='http-request,path-parameters,http-response']

[[resources-tags-bookmarks-create]]
=== 태그에 북마크 추가

operation::tags/bookmarks/create[snippets='http-request,path-parameters,http-response,response-headers']

[[resources-tags-bookmarks-delete]]
=== 태그에 북마크 삭제

operation::tags/bookmarks/delete[snippets='http-request,path-parameters,http-response']

[[resources-bookmarks]]
== Bookmarks

[[resources-bookmarks-create]]
=== 북마크 추가

operation::bookmarks/create[snippets='http-request,request-fields,http-response,response-headers,response-fields']

[[resources-bookmarks-get]]
=== 특정 북마크 조회

operation::bookmarks/get[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-bookmarks-get-list]]
=== 북마크 전체 조회

operation::bookmarks/get/list[snippets='http-request,http-response,response-fields']

[[resources-bookmarks-delete]]
=== 북마크 삭제

operation::bookmarks/delete[snippets='http-request,path-parameters,http-response']
