ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-bookmarks]]
== Bookmarks

[[resources-bookmarks-create]]
=== 북마크 추가

operation::bookmarks/create[snippets='http-request,request-fields,http-response,response-body,response-headers']

[[resources-bookmarks-get]]
=== 북마크 조회

operation::bookmarks/get[snippets='http-request,request-body,http-response,response-body']

[[resources-bookmarks-get-list]]
=== 북마크 전체 조회

operation::bookmarks/get/list[snippets='http-request,request-body,http-response,response-body']

[[resources-bookmarks-delete]]
=== 북마크 삭제

operation::bookmarks/delete[snippets='http-request,request-body,http-response,response-body']

[[resources-tags]]
== Tags

[[resources-tags-create]]
=== 태그 추가

operation::tags/create[snippets='http-request,request-fields,http-response,response-body,response-headers']

[[resources-tags-get]]
=== 태그 조회

operation::tags/get[snippets='http-request,request-body,http-response,response-body,response-fields']

[[resources-tags-get-list]]
=== 태그 전체 조회

operation::tags/get/list[snippets='http-request,request-body,http-response,response-body,response-fields']

[[resources-tags-delete]]
=== 태그 삭제

operation::tags/delete[snippets='http-request,request-body,http-response,response-body']

[[resources-tags-tagbookmark]]
=== 태그에 북마크 추가

operation::tags/tagBookmark[snippets='http-request,http-response,response-body,response-headers']

[[resources-tags-category]]
=== 태그의 카테고리 수정

operation::tags/category[snippets='http-request,http-response']
