ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-users]]
== Users

[[resources-users-get-info]]
=== 정보 가져 오기

operation::users/get/info[snippets='http-request,http-response,response-fields']

[[resources-users-update-notification-email]]
=== 알림 이메일 수정하기

operation::users/update/notification/email[snippets='http-request,request-body,request-fields,http-response']

[[resources-users-update-notification-enabled]]
=== 알림 설정 수정하기

operation::users/update/notification/enabled[snippets='http-request,request-body,request-fields,http-response']

[[resources-users-delete]]
=== 회원 탈퇴

operation::users/delete[snippets='http-request,http-response']

[[resources-categories]]
== Categories

[[resources-categories-create]]
=== 카테고리 추가

operation::categories/create[snippets='http-request,request-fields,http-response,response-headers,response-fields']

[[resources-categories-get-list]]
=== 카테고리 전체 조회

operation::categories/get/List[snippets='http-request,http-response,response-fields']

[[resources-categories-update]]
=== 카테고리 수정

operation::categories/update[snippets='http-request,request-fields,http-response']

[[resources-categories-delete]]
=== 카테고리 삭제

operation::categories/delete[snippets='http-request,path-parameters,http-response']

[[resources-tags]]
== Tags

[[resources-tags-create]]
=== 태그 추가

operation::tags/create[snippets='http-request,request-fields,http-response,response-headers,response-fields']

[[resources-categories-tags-update]]
=== 태그가 속한 카테고리 수정

operation::categories/tags/update[snippets='http-request,path-parameters,http-response']

[[resources-tags-delete]]
=== 태그 삭제

operation::tags/delete[snippets='http-request,path-parameters,http-response']

[[resources-bookmarks]]
== Bookmarks

[[resources-bookmarks-create]]
=== 북마크 추가

operation::bookmarks/create[snippets='http-request,request-fields,http-response,response-headers,response-fields']

[[resources-bookmarks-get-list]]
=== 북마크 전체 조회

operation::bookmarks/get/list[snippets='http-request,request-parameters,http-response,response-fields']

[[resources-bookmarks-delete]]
=== 북마크 삭제

operation::bookmarks/delete[snippets='http-request,path-parameters,http-response']

[[resources-tagbookmark]]
== Tag & Bookmark

[[resources-tags-get]]
=== 특정 태그에 속한 북마크 조회

operation::tags/bookmarks/get[snippets='http-request,request-parameters,path-parameters,http-response,response-fields']

[[resources-tags-untagged-get]]
=== 태그가 등록되지 않은 북마크 조회

operation::tags/bookmarks/untagged/get[snippets='http-request,request-parameters,http-response,response-fields']

[[resources-tags-bookmarks-create]]
=== 북마크에 태그 등록

operation::tags/bookmarks/create[snippets='http-request,path-parameters,http-response,response-headers']

[[resources-tags-bookmarks-delete]]
=== 북마크에 등록된 태그 삭제

operation::tags/bookmarks/delete[snippets='http-request,path-parameters,http-response']

[[resources-bookmarks-get]]
=== 북마크에 등록된 태그 조회

operation::bookmarks/tags/get[snippets='http-request,path-parameters,http-response,response-fields']
