spring:
  profiles:
    active: local
    include:
      - db

---
spring:
  profiles: local

logging:
  config: classpath:logback-local.xml

---
spring:
  profiles: prod

logging:
  config: classpath:logback-prod.xml
---

spring:
  h2:
    console:
      enabled: true
      path: /h2-console