spring:
  application:
    name: taggle-logback
  profiles:
    active: local
  jpa.properties.hibernate:
    show_sql: true
    format_sql: true
    use_sql_comments: true
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:testdb

logging.level.org.hibernate.type.descriptor.sql: trace

---

spring:
  profiles: local

logging:
  config: classpath:logback-local.xml

---
spring:
  profiles: prod

logging:
  config: classpath:logback-prod.xml

---
